variables:
    ASSETCONTAINER_NAME: "vsto-assets-$CI_BUILD_REF"

stages:
    - build

before_script:
    - echo %CI_BUILD_ID%
    - echo %CI_BUILD_REF%
    - echo %CI_BUILD_REF_NAME%
    - echo %CI_BUILD_REPO%
    - echo %CI_BUILD_TAG%
    - echo %CI_BUILD_NAME%
    - echo %CI_BUILD_STAGE%
    - echo %CI_BUILD_TRIGGERED%
    - echo %CI_PROJECT_DIR%
    - echo %CI_PROJECT_ID%
    - echo %CI_SERVER%
    - echo %CI_SERVER_NAME%
    - echo %CI_SERVER_REVISION%
    - echo %CI_SERVER_VERSION%
    
docker-build:
    stage: build
    only:
    - branches
    script:
    - 'echo "container name : %ASSETCONTAINER_NAME% "'
    - 'docker build 
        --build-arg MSBUILD_PROJECT=SPES-Modelverifier-Base.sln
        --build-arg MSBUILD_ARGS=/p:ApplicationVersion=%PROJECT_VERSION%.%CI_BUILD_ID%;Configuration=Release;PublishDir=C:\\SPES-Modelverifier\\%CI_BUILD_REF_NAME%\\2013-2016\\;InstallUrl=http://releases.chemsorly.com/SPES-Modelverifier/%CI_BUILD_REF_NAME%/2013-2016/;UpdateUrl=http://releases.chemsorly.com/SPES-Modelverifier/%CI_BUILD_REF_NAME%/2013-2016/
        --build-arg MSBUILD_TARGET=/t:VisioAddin2013:Publish
        -f build.Dockerfile 
        -t git.chemsorly.com/chemsorly/spes-modelverifier . '
    - docker create --name %ASSETCONTAINER_NAME%-2013-2016 git.chemsorly.com/chemsorly/spes-modelverifier
    - docker cp %ASSETCONTAINER_NAME%-2013-2016:C:\\SPES-Modelverifier\\%CI_BUILD_REF_NAME%\\ C:\\Gitlab-Releases\\SPES-Modelverifier\\
    
    - 'docker build 
        --build-arg MSBUILD_PROJECT=SPES-Modelverifier-Base.sln
        --build-arg MSBUILD_ARGS=/p:ApplicationVersion=%PROJECT_VERSION%.%CI_BUILD_ID%;Configuration=Release;PublishDir=C:\\SPES-Modelverifier\\%CI_BUILD_REF_NAME%\\2010\\;InstallUrl=http://releases.chemsorly.com/SPES-Modelverifier/%CI_BUILD_REF_NAME%/2010/;UpdateUrl=http://releases.chemsorly.com/SPES-Modelverifier/%CI_BUILD_REF_NAME%/2010/
        --build-arg MSBUILD_TARGET=/t:VisioAddin2010:Publish
        -f build.Dockerfile 
        -t git.chemsorly.com/chemsorly/spes-modelverifier . '
    - docker create --name %ASSETCONTAINER_NAME%-2010 git.chemsorly.com/chemsorly/spes-modelverifier
    - docker cp %ASSETCONTAINER_NAME%-2010:C:\\SPES-Modelverifier\\%CI_BUILD_REF_NAME%\\ C:\\Gitlab-Releases\\SPES-Modelverifier\\

after_script:
    - docker rm %ASSETCONTAINER_NAME%-2013-2016 -f
    - docker rm %ASSETCONTAINER_NAME%-2010 -f
    - powershell docker rmi $(docker images -q -f dangling=true) -f